version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.4.2
  sonarcloud: extendaretail/sonarcloud@0.0.2
jobs:
  notify:
    docker:
      - image: cimg/node:15.1
    steps:
      - slack/notify:
          custom: |
            {
              "text": "CircleCI job start!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Start Building...",
                    "emoji": true
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: always
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Static code Analysis
          command: |
            npm i -D sonarqube-scanner
            ./node_modules/sonarqube-scanner/dist/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      - persist_to_workspace:
          root: .
          paths:
            - .scannerwork/report-task.txt
      - sonarcloud/check_quality_gate
      - slack/notify:
          event: fail
          mentions: '@Nico'
          template: basic_fail_1
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - slack/notify:
          event: fail
          mentions: '@Nico'
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: '@Nico'
          template: success_tagged_deploy_1
workflows:
  build-test-and-deploy:
    jobs:
      - notify:
          context: slack-secrets
      - build-and-test:
          context:
            - slack-secrets
            - sonarcloud
      - deploy:
          context: slack-secrets
          requires:
            - build-and-test
