version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  build:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
  test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - run:
          name: Run tests
          command: npm test
  sonar:  
    docker:
      - image: cimg/node:15.1
    steps:
      - sonarcloud/scan
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - heroku/deploy-via-git
  notify:  
    docker:
      - image: cimg/node:15.1
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Start Building...*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - slack/notify:
          event: fail
          mentions: '@Nico'
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: '@Nico'
          template: success_tagged_deploy_1
workflows:
  build-test-and-deploy: 
    jobs:
      - sonar
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - sonar
            - test
      - notify:
          context: slack-secrets
          filters:
            tags:
              only: /^v.*/
