version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - sonarcloud/scan
      - node/install-packages
      - run:
          name: Run tests
          command: npm test      
  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - heroku/deploy-via-git
  notify:  
    docker:
      - image: cimg/node:15.1
    steps:
      - slack/notify:
          custom: |
            {
              "text": "CircleCI job start!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Start Building...",
                    "emoji": true
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: always
      - slack/notify:
          event: fail
          mentions: '@Nico'
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: '@Nico'
          template: success_tagged_deploy_1
workflows:
  build-test-and-deploy: 
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
      - notify:
          context: slack-secrets
          filters:
            tags:
              only: /^v.*/
